max_width = 120
array_width = 100
chain_width = 100
fn_call_width = 80
struct_lit_width = 60
struct_variant_width = 60
single_line_if_else_max_width = 100
overflow_delimited_expr = true
use_field_init_shorthand = true
fn_args_layout = "Compressed"